# Source: https://github.com/Garfield96/fastShell/blob/7d3260d09f8bbdfee64064f586490f92054746b1/.github/dependabot.yml
# See
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates
# for details

version: 2
updates:
  # Enable crate version updates for the main crate
  - package-ecosystem: "cargo"
    # Look `Cargo.toml` in the repository root
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
  # Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    # Set to `/` to check the Actions used in `.github/workflows`
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
